# configs/hh_experiment.yml
#
# Main configuration file for a Hodgkin-Huxley experiment.
# This file defines all parameters for the simulation, training, and evaluation.

experiment:
  name: "HH_Model_Comparison"
  # Directory where all outputs (data, models, results) for this experiment will be saved.
  output_dir: "./outputs/hh_experiment_final"
  # A list of random seeds to run. The experiment will be repeated for each seed.
  seeds: [42, 43, 44]

task:
  # The name of the scientific model to use, as defined in utils/task_setup.py
  name: "hh_model"
  # A list of low-fidelity simulation budgets to generate/use for training.
  lf_sim_budgets: [10000, 100000]
  # A list of high-fidelity simulation budgets to generate/use for training.
  hf_sim_budgets: [100, 500]

model_hyperparams:
  # A list of inference methods to train and evaluate.
  models_to_run: ["npe", "mf_npe", "sbi_npe"]

  # Number of ground-truth samples to generate for the final test set.
  num_test_samples: 100

  # --- Training Hyperparameters ---
  learning_rate: 0.0005
  finetuning_lr_factor: 10.0 # Learning rate multiplier for fine-tuning
  batch_size: 50
  validation_fraction: 0.1
  patience: 20  # For early stopping
  max_num_epochs: 200
  clip_max_norm: 5.0

  # --- Normalizing Flow Architecture ---
  z_score_x: True
  z_score_theta: True
  hidden_features: 50
  num_transforms: 5
  num_bins: 8